name =input(" what is your name ")
age =input(" what is your age ")
color =input(" what is your favourite color ")
print (f" name is {name}")
print (f" age is {age} years old")
print (f" favorite color is {color}")
